#!/bin/bash

set -ex

CURDIR=$(cd "$(dirname "$0")"; pwd -P)
NAME=youtrack
TMP=$NAME-tmp
IMG=private/$NAME

containerRunning() {
    echo `docker inspect --format="{{ .State.Running }}" $1 2> /dev/null`
}

docker build --rm -t $IMG "$CURDIR"

RUNNING=$(containerRunning $NAME)
if [ "$RUNNING" == "true"  ]; then
    docker stop $NAME
fi

if [ "$RUNNING" != "" ]; then
    docker create --name $TMP --volumes-from $NAME $IMG
    docker rm $NAME
    docker create -p 127.0.0.1:8001:8080 --restart=always --name $NAME --volumes-from $TMP $IMG
    docker rm $TMP
else
    docker create -p 127.0.0.1:8001:8080 --restart=always --name $NAME $IMG
fi

if [ "$RUNNING" == "true"  ]; then
    docker start $NAME
fi
